let err_code_list = [
    {err_code: -1, msg_En: 'UnknownError', msg_Zn: '未知错误'},
    {err_code: 0, msg_En: 'Success', msg_Zn: '成功'},
    {err_code: 2, msg_En: 'BadParameter', msg_Zn: '参数错误'},
    {err_code: 102, msg_En: 'InvalidTimeFormat', msg_Zn: '无效时间格式'},
    {err_code: 103, msg_En: 'InvalidRegisterType', msg_Zn: '无效登记类型'},
    {err_code: 104, msg_En: 'InvalidSmsCode', msg_Zn: '无效短信验证码'},
    {err_code: 106, msg_En: 'InvalidMobileFormat', msg_Zn: '无效手机号码'},
    {err_code: 107, msg_En: 'PasswordIsTooShort', msg_Zn: '密码太短'},
    {err_code: 110, msg_En: 'AdminNotExists', msg_Zn: '用户名不存在'},
    {err_code: 111, msg_En: 'AccountLocked', msg_Zn: '账户锁定'},
    {err_code: 112, msg_En: 'MobileAlreadyExists', msg_Zn: '手机号码已存在'},
    {err_code: 113, msg_En: 'UserMobileUnregistered', msg_Zn: '用户手机号未注册'},
    {err_code: 119, msg_En: 'PayPasswordNotSet', msg_Zn: '支付密码未设置'},
    {err_code: 120, msg_En: 'WrongPayPassword', msg_Zn: '支付密码错误'},
    {err_code: 138, msg_En: 'ShareNotFound', msg_Zn: '共享支付关系不存在'},
    {err_code: 200, msg_En: 'WrongUsernamePassword', msg_Zn: '用户名密码错误'},
    {err_code: 201, msg_En: 'AlreadyCheckedIn', msg_Zn: '已登录'},
    {err_code: 202, msg_En: 'NotLogin', msg_Zn: '未登录'},
    {err_code: 500, msg_En: 'InternalServerError', msg_Zn: '内部服务器错误'},
    {err_code: 501, msg_En: 'NotImplemented', msg_Zn: '未实现'},
    {err_code: 502, msg_En: 'BadGateway', msg_Zn: '错误的网关'},
    {err_code: 503, msg_En: 'ServiceUnavailable', msg_Zn: '服务不可用'},
    {err_code: 504, msg_En: 'SmsSendFailure', msg_Zn: '短信发送失败'},
    {err_code: 505, msg_En: 'FileUploadFailure', msg_Zn: '文件上传失败'},
    {err_code: 506, msg_En: 'RoleIdNotExist', msg_Zn: '角色ID不存在'},
    {err_code: 1000, msg_En: 'AppNotFound', msg_Zn: '对接账号不存在'},
    {err_code: 1001, msg_En: 'AppDisabled', msg_Zn: '对接账号已禁用'},
    {err_code: 1002, msg_En: 'PermissionDeny', msg_Zn: '没有操作权限'},
    {err_code: 1003, msg_En: 'ProductNotRegister', msg_Zn: '产品未录入'},
    {err_code: 1004, msg_En: 'WrongPassword', msg_Zn: '密码错误'},
    {err_code: 1005, msg_En: 'WrongCaptcha', msg_Zn: '验证码错误'},
    {err_code: 1006, msg_En: 'WrongSmsCode', msg_Zn: '短信验证码错误'},
    {err_code: 1007, msg_En: 'UserAlreadyExists', msg_Zn: '用户已经存在'},
    {err_code: 1008, msg_En: 'EmailAlreadyExists', msg_Zn: '邮箱已存在'},
    {err_code: 1009, msg_En: 'ChannelNotFound', msg_Zn: '渠道不存在'},
    {err_code: 1010, msg_En: 'UserNotFound', msg_Zn: '用户不存在'},
    {err_code: 1011, msg_En: 'BalanceNotEnough', msg_Zn: '余额不足'},
    {err_code: 1012, msg_En: 'FileNotFound', msg_Zn: '文件未找到'},
    {err_code: 1013, msg_En: 'FileAlreadyUsed', msg_Zn: '文件已使用'},
    {err_code: 1014, msg_En: 'UserDisabled', msg_Zn: '用户被禁用'},
    {err_code: 1100, msg_En: 'AgreementSignIncomplete', msg_Zn: '相关协议未签署完全'},
    {err_code: 1101, msg_En: 'AgreementNotSign', msg_Zn: '协议未签署'},
    {err_code: 1102, msg_En: 'AgreementNotFound', msg_Zn: '协议不存在'},
    {err_code: 1103, msg_En: 'RecordNotFound', msg_Zn: '未找到记录'},
    {err_code: 1104, msg_En: 'CouponNotFound', msg_Zn: '未找到优惠券'},
    {err_code: 1105, msg_En: 'CouponNotMatch', msg_Zn: '信息不匹配'},
    {err_code: 1106, msg_En: 'CouponUsed', msg_Zn: '优惠券已使用'},
    {err_code: 1107, msg_En: 'CouponExpired', msg_Zn: '优惠券已过期'},
    {err_code: 1108, msg_En: 'OrderNotFound', msg_Zn: '订单未找到'},
    {err_code: 1109, msg_En: 'OrderPaid', msg_Zn: '订单已支付'},
    {err_code: 1110, msg_En: 'OrderCanceled', msg_Zn: '订单已取消'},
    {err_code: 1111, msg_En: 'OrderInvalid', msg_Zn: '订单无效'},
    {err_code: 1112, msg_En: 'CargoNotFound', msg_Zn: '未发现运单信息'},
    {err_code: 1113, msg_En: 'OrderExpired', msg_Zn: '订单已过期'},
    {err_code: 1115, msg_En: 'OrderAlreadyChecked', msg_Zn: '订单已审核通过'},
    {err_code: 1116, msg_En: 'OrderUnpaid', msg_Zn: '订单未支付'},
    {err_code: 1200, msg_En: 'CompanyNotFound', msg_Zn: '公司名称为空'},
    {err_code: 1201, msg_En: 'CompanyAlreadyExists', msg_Zn: '公司已存在'},
    {err_code: 1300, msg_En: 'ArticleNotFound', msg_Zn: '文章未找到'},
    {err_code: 1301, msg_En: 'ArticleDisabled', msg_Zn: '文章禁用'},
    {err_code: 1400, msg_En: 'CategoryNotFound', msg_Zn: '目录未找到'},
    {err_code: 1401, msg_En: 'CategoryDisabled', msg_Zn: '目录禁用'},
    {err_code: 1500, msg_En: 'RequestRecordNotFound', msg_Zn: '申请单记录未找到'},
    {err_code: 1509, msg_En: 'RequestAmountNotMatch', msg_Zn: '申请单金额与实际值不匹配'},
    {err_code: 1510, msg_En: 'RequestAmountNotEnough', msg_Zn: '申请单金额不足最低金额'},
    {err_code: 1511, msg_En: 'RequestAmountExceeded', msg_Zn: '申请单金额超限'},
    {err_code: 1512, msg_En: 'RequestNotPermitted', msg_Zn: '申请未获得该项权限'},
    {err_code: 1513, msg_En: 'RequestAlreadyChecked', msg_Zn: '申请单已审核通过，不可更改'},
    {err_code: 1600, msg_En: 'PriceNotFound', msg_Zn: '价格方案未找到'},
    {err_code: 1601, msg_En: 'MatchAlreadyExists', msg_Zn: '匹配已存在'},
    {err_code: 1602, msg_En: 'MatchNotFound', msg_Zn: '匹配未找到'},
];

export const check_err_code = (val, fn1, fn2) => {
    let rtn = err_code_list.filter((item, index) => {
        return val === item.err_code
    })[0];
    if (rtn.err_code === 0) {
        fn1(rtn)
    } else {
        fn2(rtn)
    }
};
